[BUILD]

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -427,14 +427,13 @@ jobs:
       shell: bash
       run: |
         grep --file=$GITHUB_WORKSPACE/.log_errors "${{ runner.workspace }}/FreeCAD_installed.log" || true
-        # grep --file=$GITHUB_WORKSPACE/.log_errors "${{ runner.workspace }}/FreeCAD_installed.log" ; [ $? == 1 ] && \
-        # echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || \
-        # ( echo "::warning::Error from .log_errors found!" && false )
+        grep --file=$GITHUB_WORKSPACE/.log_errors "${{ runner.workspace }}/FreeCAD_installed.log" ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "::warning::Error from .log_errors found!" && false )
 
     - name: Package
       shell: bash
       run: |
-        cpack -G "ZIP" "${{ runner.workspace }}/build"
+        cd "${{ runner.workspace }}/build"
+        cpack -G "ZIP"
 
     - name: Upload Package
       uses: actions/upload-artifact@v2
