[BUILD]

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -408,12 +408,20 @@ jobs:
         node ss.js
 
 
-    - name: 'Upload Screenshot'
+    - name: Upload Screenshot
       uses: actions/upload-artifact@v2
       with:
         name: ${{ steps.matrix-name.outputs.concat }}-Screenshot
         path: FreeCAD.jpg
         retention-days: 1
+
+    - name: Check run log
+      shell: bash
+      run: |
+        cat /tmp/FreeCAD_installed.log
+        grep --file=${{ runner.workspace }}/.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && \
+        echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || \
+        ( echo "::warning::Error from .log_errors found!" && false )
 
     - name: Install and Test (Linux)
       if: runner.os == 'LinuxDISABLED'
